"""
saptial_CR.py: file taking in imput a dataframe in pkl form and running the spatial version of the networks specified inside

OUTPUTS a pickle file with         data['last_2_frames_N'] = last_2_frames_N
                                   data['current_R']       = current_R
                                   data['current_N']       = current_N
                                   data['g_rates']         = g_rates
                                   data['s_list']          = s_list
                                   data['abundances']      = abundances[::100]
                                   data['t_list']          = t_list
                                   data['biomass']         = biomass
        inside the dedicated Data folder, in addition to the same columns that the input dataframe already had

"""

import os
import sys
import pickle
import ast

import pandas as pd
import numpy as np

from pathlib import Path

path = os.path.splitext(os.path.abspath(__file__))[0]
base_path = path.split('CRIMMES/MODEL')[0]
module_path = f'{base_path}/CRIMMES/MODEL/shared_scripts'

# Add the directory to sys.path
if module_path not in sys.path:
    sys.path.append(module_path)

import N_dynamics
import R_dynamics
import update

#----------------------------------------------------------------------------------------------------------------------
# import dataframe of networks already run and mapped
# as an example here we use the ones from the CR_to_LV file 
pickle_file_path = Path('path to pickle file generated by CR_to_LV notebook')

df = pd.read_pickle(pickle_file_path)
#----------------------------------------------------------------------------------------------------------------------

def spatial_CR(i):

    """
    i: int, index in the dataframe of the network to run

    """

    # create paths to save results
    # create paths to save results, these are examples, ad they will end up in the Data folder
    path = f'{base_path}/CRIMMES/MODEL/Data/spatial_CR'
    results_dir = f"{path}_results/{i}"
    os.makedirs(results_dir, exist_ok=True)

    n=100
    n_s=8

    # defining binary uptake matrix with 5 preferences for each species
    up_mat = df['C'][i][0]  
    n_r = up_mat.shape[1]

    # defining sign matrix (all positive nutrients here)
    sign_mat = np.ones((n_s,n_r))

    # no essential nutrients (only catabolic cross-feeding)
    mat_ess = np.zeros((n_s,n_r))

    # no auxotrophies (anyone can produce what metabolism allows)
    spec_met = np.ones((n_s,n_r))

    # create metabolic matrix of sparcity 0. with entries sampled from Dirichelet distribution: everyone produces everything
    met_mat = df['D'][i][0]

    # recapitulate in dictionary
    mat = {
        'uptake'  : up_mat,
        'met'     : met_mat,
        'ess'     : mat_ess,
        'spec_met': spec_met,
        'sign'    : sign_mat
    }

    # definition of the rest of the model parameters

    # set dilution
    param = df['param_dict'][i]
    if isinstance(param, str):
        # Evaluate the string with numpy's array
        param = eval(param, {"array": np.array})
    param=param[0]
    
    param['n']=100                                 
    param['sor']=1.55
    param['L']=100
    param['D']=10
    param['Dz']=1e-4
    param['acc']=1e-5             

    # rescale influx so that wm and space compare in terms of supplied energy
    param['ext']=param['ext']/param['tau']

    # simulate in space
    # initial guesses and conditions
    R_space_ig = np.zeros((n,n,n_r))
    R_space_ig[:,:,param['ext']>0.]=param['ext'][0]/2
    N0_space   = np.zeros((n,n))
    N0_space   = N_dynamics.encode(np.random.randint(0, n_s, size=(n,n)),np.array(np.arange(n_s)))
    biomass = np.random.uniform(0, 2, (n, n)) 

    # define functions
    fR = R_dynamics.f
    gr = N_dynamics.growth_rates

    # spatial
    last_2_frames_N, _, current_R, current_N, g_rates, s_list, abundances, t_list, biomass  = update.simulate_3D_NBC(150000, fR, gr, R_space_ig, N0_space, biomass, param, mat)

    data = {
                                        'n_supplied': df['n_supplied'],
                                        'n_consumed': df['n_consumed'],
                                        'n_produced': df['n_produced'],
                                        'structure':  df['structure'],
                                        'leakage': df['leakage'],
                                        'parameters':param,
                                        'replica':df['replica'],
                                        'uptake':up_mat,
                                        'D':met_mat,
                                        'CR_R':df['R_cr'], 
                                        'CR_N':df['N_cr'], 
                                        'LV': df['N_lv'],
                                        'g0':df['g'],
                                        'A':df['A']
                                    }

    data['last_2_frames_N'] = last_2_frames_N
    data['current_R']       = current_R
    data['current_N']       = current_N
    data['g_rates']         = g_rates
    data['s_list']          = s_list
    data['abundances']      = abundances[::100]
    data['t_list']          = t_list
    data['biomass']         = biomass

    # output file path
    output_file = f'{results_dir}/all_data.pkl'

    # save as pickle
    with open(output_file, 'wb') as file:
        pickle.dump(data, file)

    return 

    
#------------------------------------------------------------------------------------------------------------

if __name__ == "__main__":
    
    # Check if there are command-line arguments
    if len(sys.argv) == 2:
        i = int(sys.argv[1])

        # Run the simulation with the provided parameters
        spatial_CR(i)
        print(f"Simulation completed for row number {i}")

    else:
        print("Usage: python spatial_CR.py")
